"""Upgrade table Hotels, Column id

Revision ID: 87d06482a2f5
Revises: 956f92fac1a4
Create Date: 2024-11-02 16:55:24.797656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d06482a2f5'
down_revision: Union[str, None] = '956f92fac1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
