"""Update table users, Column id 

Revision ID: e031a4128fb1
Revises: 2d5363eb64ce
Create Date: 2024-11-02 16:25:01.980699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e031a4128fb1'
down_revision: Union[str, None] = '2d5363eb64ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
